# Generated by Django 5.2.5 on 2025-08-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_alter_postmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='content_type',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Mobile App Development', 'Mobile App Development'), ('Data Science', 'Data Science'), ('Cybersecurity', 'Cybersecurity'), ('Blockchain', 'Blockchain')], max_length=255),
        ),
    ]
