# Generated by Django 5.2.5 on 2025-08-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0006_commentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
