# Generated by Django 5.2.5 on 2025-08-28 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0007_alter_commentmodel_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='blog_images/')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='BlogApp.blogmodel')),
            ],
        ),
    ]
