# Generated by Django 5.2.5 on 2025-08-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0008_blogimagesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_banners/'),
        ),
    ]
